package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

const dosboxExecutable = "/Applications/DOSBox Staging.app/Contents/MacOS/dosbox"

func main() {
	version, err := runAndTrim("--version")
	if err != nil {
		exitf("failed to get DOSBox version: %v", err)
	}

	configPath, err := runAndTrim("--printconf")
	if err != nil {
		exitf("failed to get DOSBox config path: %v", err)
	}

	content, err := os.ReadFile(configPath)
	if err != nil {
		exitf("failed to read config %s: %v", configPath, err)
	}

	settings := []struct {
		GoName  string
		ConfKey string
	}{
		{GoName: "MachineOptions", ConfKey: "machine"},
		{GoName: "CPUCoreOptions", ConfKey: "core"},
		{GoName: "CPUTypeOptions", ConfKey: "cputype"},
		{GoName: "SoundBlasterOptions", ConfKey: "sbtype"},
		{GoName: "JoystickTypeOptions", ConfKey: "joysticktype"},
	}

	valuesByName := map[string][]string{}
	for _, setting := range settings {
		values, err := extractPossibleValues(string(content), setting.ConfKey)
		if err != nil {
			exitf("failed to extract %s: %v", setting.ConfKey, err)
		}
		valuesByName[setting.GoName] = values
	}

	output := renderGeneratedFile(filepath.Clean(configPath), firstLine(version), settings, valuesByName)
	target := filepath.Join("internal", "machine", "options_generated.go")
	if err := os.WriteFile(target, []byte(output), 0o644); err != nil {
		exitf("failed to write %s: %v", target, err)
	}
}

func runAndTrim(arg string) (string, error) {
	cmd := exec.Command(dosboxExecutable, arg)
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(output)), nil
}

func extractPossibleValues(content, setting string) ([]string, error) {
	pattern := fmt.Sprintf(`(?ms)^#\s+%s:.*?^#\s+Possible values:\s*(.+?)\.\s*$`, regexp.QuoteMeta(setting))
	re := regexp.MustCompile(pattern)
	matches := re.FindStringSubmatch(content)
	if len(matches) != 2 {
		return nil, fmt.Errorf("setting %q not found", setting)
	}

	parts := strings.Split(matches[1], ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		value := strings.TrimSpace(part)
		if value == "" {
			continue
		}
		values = append(values, canonicalValue(value))
	}

	values = compactStable(values)
	if len(values) == 0 {
		return nil, fmt.Errorf("setting %q has no values", setting)
	}
	return values, nil
}

func canonicalValue(value string) string {
	switch value {
	case "none/off":
		return "none"
	default:
		return value
	}
}

func compactStable(values []string) []string {
	seen := map[string]struct{}{}
	result := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		result = append(result, value)
	}
	return result
}

func renderGeneratedFile(configPath, version string, settings []struct {
	GoName  string
	ConfKey string
}, valuesByName map[string][]string) string {
	var buffer bytes.Buffer

	buffer.WriteString("// Code generated by go run ./cmd/generate-options; DO NOT EDIT.\n")
	buffer.WriteString(fmt.Sprintf("// Source: %s\n", configPath))
	buffer.WriteString(fmt.Sprintf("// DOSBox version: %s\n\n", version))
	buffer.WriteString("package machine\n\n")

	sorted := slices.Clone(settings)
	slices.SortFunc(sorted, func(a, b struct {
		GoName  string
		ConfKey string
	}) int {
		return strings.Compare(a.GoName, b.GoName)
	})

	for _, setting := range sorted {
		buffer.WriteString(fmt.Sprintf("var %s = []string{\n", setting.GoName))
		for _, value := range valuesByName[setting.GoName] {
			buffer.WriteString(fmt.Sprintf("\t%q,\n", value))
		}
		buffer.WriteString("}\n\n")
	}

	return buffer.String()
}

func firstLine(value string) string {
	lines := strings.Split(value, "\n")
	return strings.TrimSpace(lines[0])
}

func exitf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
