package machine

func NewProfile() Profile {
	return Profile{
		Name:              "New Machine",
		Description:       "",
		CPUCore:           "auto",
		CPUType:           "486",
		Cycles:            "25000",
		Machine:           "svga_s3",
		MemoryMB:          16,
		SoundBlaster:      "sb16",
		MouseCapture:      "onclick",
		MouseRawInput:     true,
		DOSMouseImmediate: false,
		FloppyDiskImages:  nil,
		HardDiskImage:     "",
		HardDiskCHS:       "",
		JoystickType:      "auto",
		GUS:               false,
		XMS:               true,
		EMS:               true,
		UMB:               true,
	}
}

func StarterProfiles() []Profile {
	return []Profile{
		{
			Name:              "286 EGA",
			Description:       "Low-end late 80s setup for EGA adventure and strategy titles.",
			CPUCore:           "normal",
			CPUType:           "386",
			Cycles:            "1200",
			FixedCycles:       false,
			Machine:           "ega",
			MemoryMB:          2,
			SoundBlaster:      "sbpro1",
			MouseCapture:      "seamless",
			MouseRawInput:     false,
			DOSMouseImmediate: true,
			GUS:               false,
			JoystickType:      "disabled",
			XMS:               true,
			EMS:               true,
			UMB:               true,
		},
		{
			Name:              "486 SVGA",
			Description:       "Balanced early 90s machine for VGA DOS games with Sound Blaster 16.",
			CPUCore:           "auto",
			CPUType:           "486",
			Cycles:            "25000",
			FixedCycles:       false,
			Machine:           "svga_et4000",
			MemoryMB:          16,
			SoundBlaster:      "sb16",
			MouseCapture:      "onclick",
			MouseRawInput:     true,
			DOSMouseImmediate: false,
			GUS:               false,
			JoystickType:      "auto",
			XMS:               true,
			EMS:               true,
			UMB:               true,
		},
		{
			Name:              "Fast Pentium",
			Description:       "High-end DOS setup for demanding SVGA and Build engine games.",
			CPUCore:           "dynamic",
			CPUType:           "pentium",
			Cycles:            "50000",
			FixedCycles:       false,
			Machine:           "svga_s3",
			MemoryMB:          32,
			SoundBlaster:      "sb16",
			MouseCapture:      "onclick",
			MouseRawInput:     true,
			DOSMouseImmediate: false,
			GUS:               true,
			JoystickType:      "auto",
			XMS:               true,
			EMS:               true,
			UMB:               true,
		},
		{
			Name:              "386",
			Description:       "Basic mid-end 386 with a Sound Blaster Pro.",
			CPUCore:           "normal",
			CPUType:           "386",
			Cycles:            "3000",
			FixedCycles:       false,
			Machine:           "svga_paradise",
			MemoryMB:          4,
			SoundBlaster:      "sbpro2",
			MouseCapture:      "onclick",
			MouseRawInput:     true,
			DOSMouseImmediate: false,
			GUS:               false,
			JoystickType:      "auto",
			XMS:               true,
			EMS:               true,
			UMB:               true,
		},
	}
}
