// Code generated by go run ./cmd/generate-options; DO NOT EDIT.
// Source: /Users/nizmow/Library/Preferences/DOSBox/dosbox-staging.conf
// DOSBox version: dosbox-staging, version 0.82.2 (5e2ba)

package machine

var CPUCoreOptions = []string{
	"auto",
	"dynamic",
	"normal",
	"simple",
}

var CPUTypeOptions = []string{
	"auto",
	"386",
	"386_fast",
	"386_prefetch",
	"486",
	"pentium",
	"pentium_mmx",
}

var JoystickTypeOptions = []string{
	"auto",
	"2axis",
	"4axis",
	"4axis_2",
	"fcs",
	"ch",
	"hidden",
	"disabled",
}

var MachineOptions = []string{
	"hercules",
	"cga_mono",
	"cga",
	"pcjr",
	"tandy",
	"ega",
	"svga_s3",
	"svga_et3000",
	"svga_et4000",
	"svga_paradise",
	"vesa_nolfb",
	"vesa_oldvbe",
}

var MouseCaptureOptions = []string{
	"seamless",
	"onclick",
	"onstart",
	"nomouse",
}

var SoundBlasterOptions = []string{
	"gb",
	"sb1",
	"sb2",
	"sbpro1",
	"sbpro2",
	"sb16",
	"ess",
	"none",
}
