// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed app_icon.png
var ResourceAppiconPngData []byte
var ResourceAppiconPng = &fyne.StaticResource{
	StaticName:    "app_icon.png",
	StaticContent: ResourceAppiconPngData,
}
